# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        /:year/:month/:day/:title.html

# Setup
title:            Mert Kara
tagline:          'worst-case scenarist'
description:      'A software developer with MacGyver like skills'
url:              http://amertkara.github.io

author:
  name:           'Mert Kara'
  url:            https://amertkara.github.io

paginate:         5

# Custom vars
version:          ∞

github:
  repo:           